# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    env:
      - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
      - 'TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}'
    entrypoint:
      bash
    args:
      - '-c'
      - |
        docker build \
          --build-arg GCLOUD_TAG=$_GCLOUD_TAG \
          --build-arg NODE_TAG=$_NODE_TAG \
          --build-arg PROJECT_ID=$PROJECT_ID \
          --build-arg TERRAFORM_VERSION=${_TERRAFORM_VERSION} \
          --build-arg TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM} \
          --tag gcr.io/${PROJECT_ID}/terraform:gcloud-${_GCLOUD_TAG} \
          --tag gcr.io/${PROJECT_ID}/terraform:node-${_NODE_TAG} \
          --tag gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION} \
          .
images:
  - 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  - 'gcr.io/${PROJECT_ID}/terraform:gcloud-${_GCLOUD_TAG}'
  - 'gcr.io/${PROJECT_ID}/terraform:node-${_NODE_TAG}'
tags:
  - cloud-builders-community
  - engineering11
substitutions:
  _GCLOUD_TAG: 410.0.0
  _NODE_TAG: 16.14.0-buster
  _TERRAFORM_VERSION: 1.3.6
  _TERRAFORM_VERSION_SHA256SUM: bb44a4c2b0a832d49253b9034d8ccbd34f9feeb26eda71c665f6e7fa0861f49b