---
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    secretEnv:
      - engineering11_npm_auth_token
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build \
          --build-arg FIREBASE_TAG="${_FIREBASE_TAG}" \
          --build-arg GCLOUD_TAG="${_GCLOUD_TAG}" \
          --build-arg NODE_TAG="${_NODE_TAG}" \
          --build-arg ENGINEERING11_NPM_AUTH_TOKEN="$$engineering11_npm_auth_token" \
          --build-arg PROJECT_ID="${PROJECT_ID}" \
          --platform linux/x86_64 \
          --ulimit nofile=128000:128000 \
          --tag gcr.io/${PROJECT_ID}/engineering11:${_ENGINEERING11_TAG} \
          --tag gcr.io/${PROJECT_ID}/engineering11:firebase-${_FIREBASE_TAG} \
          --tag gcr.io/${PROJECT_ID}/engineering11:gcloud-${_GCLOUD_TAG} \
          --tag gcr.io/${PROJECT_ID}/engineering11:node-${_NODE_TAG} \
          .
images:
  - 'gcr.io/${PROJECT_ID}/engineering11:${_ENGINEERING11_TAG}'
  - 'gcr.io/${PROJECT_ID}/engineering11:firebase-${_FIREBASE_TAG}'
  - 'gcr.io/${PROJECT_ID}/engineering11:gcloud-${_GCLOUD_TAG}'
  - 'gcr.io/${PROJECT_ID}/engineering11:node-${_NODE_TAG}'
tags:
  - cloud-builders-community
  - engineering11
substitutions:
  _ENGINEERING11_TAG: 1.0.0
  _FIREBASE_TAG: 11.8.0
  _GCLOUD_TAG: 410.0.0
  _NODE_TAG: 16.14.0-buster
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/engineering11_npm_auth_token/versions/latest
      env: engineering11_npm_auth_token
