---
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    secretEnv:
      - engineering11_npm_auth_token
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build \
          --build-arg NPM_TOKEN="$$engineering11_npm_auth_token" \
          --platform linux/x86_64 \
          --ulimit nofile=128000:128000 \
          --tag gcr.io/${PROJECT_ID}/firebase:12.8.0 \
          --tag gcr.io/${PROJECT_ID}/firebase:gcloud-453.0.0 \
          --tag gcr.io/${PROJECT_ID}/firebase:node-16.14.0-buster \
          --tag gcr.io/${PROJECT_ID}/firebase:${_TAG1} \
          --tag gcr.io/${PROJECT_ID}/firebase:${_TAG2} \
          .
images:
  - 'gcr.io/${PROJECT_ID}/firebase:12.8.0'
  - 'gcr.io/${PROJECT_ID}/firebase:gcloud-453.0.0'
  - 'gcr.io/${PROJECT_ID}/firebase:node-20.9.0-buster'
  - 'gcr.io/${PROJECT_ID}/firebase:${_TAG1}'
  - 'gcr.io/${PROJECT_ID}/firebase:${_TAG2}'
tags: ['cloud-builders-community']
substitutions:
  _TAG1: nodejs20
  _TAG2: workspaces
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/engineering11_npm_auth_token/versions/latest
      env: engineering11_npm_auth_token
