---
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build \
          --build-arg NPM_TOKEN="$$engineering11_npm_auth_token" \
          --platform linux/x86_64 \
          --ulimit nofile=128000:128000 \
          --tag gcr.io/${PROJECT_ID}/firebase:node-${_NODE_TAG} \
          --tag gcr.io/${PROJECT_ID}/firebase:gcloud-${_GCLOUD_TAG} \
          --tag gcr.io/${PROJECT_ID}/firebase:${_FIREBASE_TAG} \
          .
images:
  - 'gcr.io/${PROJECT_ID}/firebase:node-${_NODE_TAG}'
  - 'gcr.io/${PROJECT_ID}/firebase:gcloud-${_GCLOUD_TAG}'
  - 'gcr.io/${PROJECT_ID}/firebase:${_FIREBASE_TAG}'
tags: ['cloud-builders-community', 'engineering11']
substitutions:
  _GCLOUD_TAG: 410.0.0
  _FIREBASE_TAG: 11.8.0
  _NODE_TAG: 16.14.0-buster
