---
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    secretEnv:
      - engineering11_npm_auth_token
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build \
          --build-arg NPM_TOKEN="$$engineering11_npm_auth_token" \
          --ulimit nofile=128000:128000 \
          -t gcr.io/${PROJECT_ID}/firebase \
          .
images:
  - 'gcr.io/${PROJECT_ID}/firebase'
tags: ['cloud-builders-community']
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/engineering11_npm_auth_token/versions/latest
      env: engineering11_npm_auth_token
