---
steps:
  - id: setup-home-and-workspace
    name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    secretEnv:
      - npm_token
    args:
      - '-c'
      - |
        echo "Setting up HOME and workspace"
        cat > ~/.npmrc <<EOH
        ${npm_token}
        EOH
        . /usr/local/lib/utils.bash
        print_versions node npm firebase gcloud
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.']
images:
  - 'gcr.io/$PROJECT_ID/firebase'
tags: ['cloud-builders-community']
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/npm_token/versions/latest
      env: npm_token
