---
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    secretEnv:
      - npm_token
    args:
      - 'build'
      - '--build-arg'
      - "NPM_TOKEN=${npm_token}"
      - '--ulimit'
      - 'nofile=128000:128000'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/firebase'
      - '.'
images:
  - 'gcr.io/${PROJECT_ID}/firebase'
tags: ['cloud-builders-community']
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/npm_token/versions/latest
      env: npm_token
