---
steps:
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    secretEnv:
      - engineering11_npm_auth_token
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build \
          --build-arg NPM_TOKEN="$$engineering11_npm_auth_token" \
          --platform linux/x86_64
          --ulimit nofile=128000:128000 \
          --tag gcr.io/${PROJECT_ID}/firebase:${_TAG1} \
          --tag gcr.io/${PROJECT_ID}/firebase:${_TAG2} \
          .
images:
  - 'gcr.io/${PROJECT_ID}/firebase:${_TAG1}'
  - 'gcr.io/${PROJECT_ID}/firebase:${_TAG2}'
tags: ['cloud-builders-community']
substitutions:
  _TAG1: node16
  _TAG2: legacy-peer-deps
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/engineering11_npm_auth_token/versions/latest
      env: engineering11_npm_auth_token
